# Generated by Django 4.0 on 2021-12-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='func',
        ),
    ]
