# Generated by Django 4.0 on 2021-12-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teja', '0002_rename_details_func'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='func',
            new_name='next',
        ),
    ]
